DIR_LEXER = lexer
DIR_PARSER = parser
DIR_SEMANTIC = semantic
DIR_TRANSPILER = transpiler

lexer:
	$(MAKE) --no-print-directory -C $(DIR_LEXER)

clean:
	$(MAKE) --no-print-directory -C $(DIR_LEXER) clean
	rm -f **/*.o **/*.out **/*.exe **/.*.cpp